services:
  bot:
    image: hyperf0rm/guild_queue_bot:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./guild_bot.db:/app/guild_bot.db
      - ./credentials.json:/app/credentials.json:ro
